//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBASE.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class agendamento
    {
        public int id { get; set; }
        public int id_cliente { get; set; }
        public int id_pet { get; set; }
        public int id_servico { get; set; }
        public int id_funcionario { get; set; }
        public System.DateTime data_inicio { get; set; }
        public System.DateTime data_termino { get; set; }
        public bool notificacao_enviada { get; set; }
        public bool canelamento { get; set; }
        public Nullable<System.DateTime> ultima_alteracao { get; set; }
        public string responsavel { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual pet pet { get; set; }
        public virtual servico servico { get; set; }
    }
}
