//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBASE.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cliente()
        {
            this.agendamento = new HashSet<agendamento>();
            this.cliente_pataz_entrada_produto = new HashSet<cliente_pataz_entrada_produto>();
            this.cliente_pataz_entrada_servico = new HashSet<cliente_pataz_entrada_servico>();
            this.cliente_pataz_saida_produto = new HashSet<cliente_pataz_saida_produto>();
            this.cliente_pataz_saida_servico = new HashSet<cliente_pataz_saida_servico>();
            this.pet = new HashSet<pet>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public string identidade { get; set; }
        public string cpf { get; set; }
        public string endereco { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> ultima_alteracao { get; set; }
        public string responsavel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agendamento> agendamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cliente_pataz_entrada_produto> cliente_pataz_entrada_produto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cliente_pataz_entrada_servico> cliente_pataz_entrada_servico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cliente_pataz_saida_produto> cliente_pataz_saida_produto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cliente_pataz_saida_servico> cliente_pataz_saida_servico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pet> pet { get; set; }
    }
}
