//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBASE.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente_pataz_entrada_produto
    {
        public int id { get; set; }
        public int id_cliente { get; set; }
        public int quantidade { get; set; }
        public int id_venda_produto { get; set; }
        public Nullable<System.DateTime> ultima_alteracao { get; set; }
        public string responsavel { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual venda_produto venda_produto { get; set; }
    }
}
