//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBASE.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class pet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pet()
        {
            this.agendamento = new HashSet<agendamento>();
            this.venda_servico = new HashSet<venda_servico>();
        }
    
        public int id { get; set; }
        public int id_pet_tipo { get; set; }
        public int id_cliete { get; set; }
        public string nome { get; set; }
        public string raca { get; set; }
        public string porte { get; set; }
        public string alergias { get; set; }
        public string observacao { get; set; }
        public Nullable<System.DateTime> ultima_alteraco { get; set; }
        public string respnsavel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agendamento> agendamento { get; set; }
        public virtual cliente cliente { get; set; }
        public virtual pet_tipo pet_tipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<venda_servico> venda_servico { get; set; }
    }
}
