//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBASE.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public produto()
        {
            this.estoque_entrada = new HashSet<estoque_entrada>();
            this.estoque_saida = new HashSet<estoque_saida>();
            this.promocao_produto = new HashSet<promocao_produto>();
            this.servico_produto = new HashSet<servico_produto>();
            this.venda_produto = new HashSet<venda_produto>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public string fabricante { get; set; }
        public string especificacoes { get; set; }
        public Nullable<decimal> valor_atual { get; set; }
        public Nullable<int> pataz_bonus { get; set; }
        public Nullable<int> pataz_custo { get; set; }
        public Nullable<System.DateTime> ultima_alteracao { get; set; }
        public string responasvel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estoque_entrada> estoque_entrada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estoque_saida> estoque_saida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<promocao_produto> promocao_produto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<servico_produto> servico_produto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<venda_produto> venda_produto { get; set; }
    }
}
