//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBASE.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class promocao_produto
    {
        public int id { get; set; }
        public int id_promocao { get; set; }
        public int id_produto { get; set; }
    
        public virtual produto produto { get; set; }
        public virtual promocao promocao { get; set; }
    }
}
