//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBASE.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class promocao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public promocao()
        {
            this.promocao_produto = new HashSet<promocao_produto>();
            this.promocao_servico = new HashSet<promocao_servico>();
        }
    
        public int id { get; set; }
        public string descricao { get; set; }
        public int porcentagem { get; set; }
        public System.DateTime data_inicio { get; set; }
        public System.DateTime data_termino { get; set; }
        public Nullable<System.DateTime> ultima_alteracao { get; set; }
        public string responsavel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<promocao_produto> promocao_produto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<promocao_servico> promocao_servico { get; set; }
    }
}
