//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBASE.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class servico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public servico()
        {
            this.agendamento = new HashSet<agendamento>();
            this.promocao_servico = new HashSet<promocao_servico>();
            this.servico_produto = new HashSet<servico_produto>();
            this.venda_servico = new HashSet<venda_servico>();
        }
    
        public int id { get; set; }
        public bool tipo_executante { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public Nullable<decimal> valor_atual { get; set; }
        public Nullable<int> tempo { get; set; }
        public Nullable<int> pataz_bonus { get; set; }
        public Nullable<int> pataz_custo { get; set; }
        public Nullable<System.DateTime> ultima_alteracao { get; set; }
        public string respnsavel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agendamento> agendamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<promocao_servico> promocao_servico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<servico_produto> servico_produto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<venda_servico> venda_servico { get; set; }
    }
}
