//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBASE.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class venda_servico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public venda_servico()
        {
            this.cliente_pataz_entrada_servico = new HashSet<cliente_pataz_entrada_servico>();
            this.venda_servico_pagamento = new HashSet<venda_servico_pagamento>();
        }
    
        public int id { get; set; }
        public int id_venda { get; set; }
        public int id_servico { get; set; }
        public int id_pet { get; set; }
        public int quantidade { get; set; }
        public decimal valor_unitario { get; set; }
        public int valor_unitario_pataz { get; set; }
        public decimal valor_total { get; set; }
        public int valor_total_pataz { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cliente_pataz_entrada_servico> cliente_pataz_entrada_servico { get; set; }
        public virtual pet pet { get; set; }
        public virtual servico servico { get; set; }
        public virtual venda venda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<venda_servico_pagamento> venda_servico_pagamento { get; set; }
    }
}
