//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBASE.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class venda_produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public venda_produto()
        {
            this.cliente_pataz_entrada_produto = new HashSet<cliente_pataz_entrada_produto>();
            this.venda_produto_pagamento = new HashSet<venda_produto_pagamento>();
        }
    
        public int id { get; set; }
        public int id_venda { get; set; }
        public int id_produto { get; set; }
        public int quantidade { get; set; }
        public decimal valor_unitario { get; set; }
        public int valor_unitario_pataz { get; set; }
        public decimal valor_total { get; set; }
        public int valor_total_pataz { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cliente_pataz_entrada_produto> cliente_pataz_entrada_produto { get; set; }
        public virtual produto produto { get; set; }
        public virtual venda venda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<venda_produto_pagamento> venda_produto_pagamento { get; set; }
    }
}
