//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBASE.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class venda_servico_pagamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public venda_servico_pagamento()
        {
            this.cliente_pataz_saida_servico = new HashSet<cliente_pataz_saida_servico>();
        }
    
        public int id { get; set; }
        public int id_venda_servico { get; set; }
        public Nullable<decimal> valor_total { get; set; }
        public Nullable<int> valor_total_pataz { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cliente_pataz_saida_servico> cliente_pataz_saida_servico { get; set; }
        public virtual venda_servico venda_servico { get; set; }
    }
}
