//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBASE.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class venda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public venda()
        {
            this.venda_produto = new HashSet<venda_produto>();
            this.venda_servico = new HashSet<venda_servico>();
        }
    
        public int id { get; set; }
        public System.DateTime data { get; set; }
        public int id_cliente { get; set; }
        public Nullable<System.DateTime> ultima_alteracao { get; set; }
        public string responsavel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<venda_produto> venda_produto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<venda_servico> venda_servico { get; set; }
    }
}
