//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBASE.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class veterinario_pet_tipo
    {
        public int id { get; set; }
        public int id_veterinario { get; set; }
        public int id_pet_tipo { get; set; }
    
        public virtual pet_tipo pet_tipo { get; set; }
        public virtual veterinario veterinario { get; set; }
    }
}
