//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBASE.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class veterinario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public veterinario()
        {
            this.veterinario_pet_tipo = new HashSet<veterinario_pet_tipo>();
        }
    
        public int id { get; set; }
        public int id_funcionario { get; set; }
        public string nome { get; set; }
        public string cpf { get; set; }
        public string identidade { get; set; }
        public string registro { get; set; }
        public Nullable<System.DateTime> ultima_alteracao { get; set; }
        public string responsavel { get; set; }
    
        public virtual funcionario funcionario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<veterinario_pet_tipo> veterinario_pet_tipo { get; set; }
    }
}
